CREATE SCHEMA IF NOT EXISTS exemplo AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS exemplo.USUARIOS (
   id INT NOT NULL,
   nome VARCHAR(100) NOT NULL,
   nascimento DATE,
   PRIMARY KEY (id)
);

DELETE exemplo.usuarios;

INSERT INTO exemplo.USUARIOS (ID, NOME, NASCIMENTO) VALUES (1, 'Huginho' , CURRENT_DATE());
INSERT INTO exemplo.USUARIOS (ID, NOME, NASCIMENTO) VALUES (2, 'Zezinho' , CURRENT_DATE());
INSERT INTO exemplo.USUARIOS (ID, NOME, NASCIMENTO) VALUES (3, 'Luizinho', CURRENT_DATE());