version: "3.4"
services:
  rtc-listarinformacaocliente:
    container_name: rtc-listarinformacaocliente
    image: rtc-listarinformacaocliente:latest
    extra_hosts:
      - "atf.intranet.bb.com.br:170.66.49.15"
      - "dsdb2d01.plexdes.bb.com.br:170.66.41.62"      
    user: "${myUID}:${myGroup}" 
    # command: "./mvnw compile quarkus:dev -Ddebug=8000 -gs /usr/share/java/maven-3/conf/settings.xml"
    build:
      context: ../
      dockerfile: ./Dockerfile.dev 
      args:
        - DB2_USER=$DB2_USER
        - DB2_PASSWORD=$DB2_PASSWORD
    environment:
      # Opção para jmx debug
      - JAVA_JMX_DEBUG=-Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8999 -Dcom.sun.management.jmxremote.rmi.port=8999 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      # Opção para debug remoto em java
      # - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
      #LOG
      - QUARKUS_LOG_CONSOLE_ENABLE=true
      - QUARKUS_LOG_CONSOLE_LEVEL=DEBUG
      # DATASOURCES E BANCO DE DADOS
      # - QUARKUS_DATASOURCE_URL=jdbc:h2:mem:exemplo;INIT=RUNSCRIPT FROM 'classpath:scripts/carga_testes.sql'
      # - QUARKUS_DATASOURCE_USERNAME=sa
      # - QUARKUS_DATASOURCE_PASSWORD=sa
      # - QUARKUS_DATASOURCE_DRIVER=org.h2.Driver
      - QUARKUS_HIBERNATE_ORM_LOG_SQL=true
     # Descomente estas linhas para testar usando o DB2 de desenvolvimento.  (comente as linhas do H2 acima) 
      - QUARKUS_DATASOURCE_DB_KIND=db2
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:db2://dsdb2d01.plexdes.bb.com.br:446/DSDB2D01:clientProgramName=rtc-listarinformacaocliente;clientApplicationInformation=rtc-listarinformacaocliente;
      - QUARKUS_DATASOURCE_USERNAME=${DB2_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${DB2_PASSWORD}     
      # OPENAPI - SWAGGER
      - QUARKUS_SMALLRYE_OPENAPI_PATH=/api-docs-json
      - QUARKUS_SWAGGER_UI_PATH=/api-docs
      - QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE=true
      # OPENTRACING - JAEGER
      - QUARKUS_JAEGER_SERVICE_NAME=rtc-listarinformacaocliente
      - QUARKUS_JAEGER_SAMPLER_TYPE=const
      - QUARKUS_JAEGER_SAMPLER_PARAM=1
      - QUARKUS_JAEGER_AGENT_HOST_PORT=jaeger
      - REPO_LOCAL=/temp/.m2/repository
    #    Descomentar para usar HotDeploy
    volumes:
      - $HOME/.m2/repository:/temp/.m2/repository
      - $PWD:/app
    networks:
      - rtc-listarinformacaocliente-net
    ports:
      - "8080:8080" # Server
      - "5005:5005" # DEBUG Não uilizar nos ambientes de producao/homologacao
      - "8999:8999" # DEBUG JMX Não utilizar nos ambientes de producao/homologacao 

  # =====================================================================================
  #   Imagens para executar localmente, elas ja estarão disponiveis para seu namespace
  # =====================================================================================
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - rtc-listarinformacaocliente-net
volumes:
  maven-repo:

  # ====================================================================================
  #    Configuração da rede do docker para este microservico 
  #    Default: 192.168.203.192/27
  #    Caso você já tenha subido outro microservico nesta rede, você pode executar outras
  #  usando um dos enderecos a seguir: 
  #    - 192.168.203.224/27
  #    Neste caso não se esqueça de mudar os mapeamentos das portas para o localhost para 
  #  que não haja conflito, conforme exemplo abaixo: 
  #    Microservico 1: 
  #       ports:
  #         - "8080:8080" (porta 8080 do localhost vai mapear a 8080 do microservico)
  #    Microservico 2: 
  #       ports:
  #         - "8081:8080" (porta 8081 do localhost vai mapear a 8080 do microservico)  
  # ====================================================================================
networks:
  rtc-listarinformacaocliente-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.129.0/24
